GET http://localhost:3000/alumnos

###
GET http://localhost:3000/alumnos/1


###
GET http://localhost:3000/maestros/5

###
GET http://localhost:3000/maestros

###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id": 3,
    "nombre": "Lucia",
    "carrera": "Ingenieria"

}

###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id":4,
    "nombre":"Nicole",
    "carrera":"Programación"

}

###
PUT http://localhost:3000/alumnos/11
Content-Type: application/json

{
    "id": 2,
    "nombre": "Lucia",
    "carrera": "Programación"
}

###
get http://localhost:3000/alumnos/2

###
delete http://localhost:3000/alumnos/25


###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id": 2,
    "nombre": 4153413,
    "carrera": "Programación"

}