GET http://localhost:3000/alumnos

###
GET http://localhost:3000/alumnos/1001


###
GET http://localhost:3000/maestros/5

###
GET http://localhost:3000/maestros

###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "legajo": 1006,
    "nombre": "Lucia",
    "carrera": "Ingenieria",
    "correo": "luci2007@gmail.com"

}

###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
   

}

###
PUT http://localhost:3000/alumnos/1006
Content-Type: application/json

{
     "legajo": 1006,
    "nombre": "Lucia",
    "carrera": "Ingenieria",
    "correo": "luci2007@gmail.com"
}

###
get http://localhost:3000/alumnos/2

###
delete http://localhost:3000/alumnos/25


###
POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id": 2,
    "nombre": 4153413,
    "carrera": "Programación"

}